# Generated by Django 5.0.6 on 2024-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='p', max_length=200),
            preserve_default=False,
        ),
    ]
