# Generated by Django 5.0.3 on 2024-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='D:\\django_projects\\social\\socialproject\\imageă019_avatar_male_man_person_user_icon.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
